CREATE ROLE owners LOGIN PASSWORD 'owners';
CREATE ROLE owner_1 LOGIN PASSWORD 'owner_1';
CREATE ROLE owner_2 LOGIN PASSWORD 'owner_2';

GRANT owners TO owner_1 WITH INHERIT FALSE;
GRANT owners TO owner_2 WITH INHERIT FALSE;

GRANT CONNECT, CREATE, TEMPORARY ON DATABASE postgres TO owners;
GRANT CREATE, USAGE ON SCHEMA public TO owners;


